version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: headscale-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: headscale
      POSTGRES_USER: headscale
      POSTGRES_PASSWORD: headscale_password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - headscale-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U headscale" ]
      interval: 10s
      timeout: 5s
      retries: 5

  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
    ports:
      - "8080:8080"
      - "9090:9090" # metrics endpoint
    command: serve
    restart: unless-stopped
    networks:
      - headscale-net

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    container_name: headscale-ui
    depends_on:
      - headscale
    ports:
      - "5353:8080"
    environment:
      - HEADSCALE_URL=http://headscale:8080
      - SCRIPT_NAME=/admin
    restart: unless-stopped
    networks:
      - headscale-net

networks:
  headscale-net:
    driver: bridge
